global_costmap:
  global_frame: /map
  map_topic: /map_merge/merged_map
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 200
  height: 200
  origin_x: -7.5
  origin_y: -7.5
  static_map: false
  rolling_window: true
  inflation_radius: 1.5
  resolution: 0.1
