local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 1.5
  height: 1.5
  origin_x: -0.75
  origin_y: -0.75
  resolution: 0.1
  inflation_radius: 0.5
  global_frame: /map
  robot_base_frame: base_link
